### ISSUE TITLE
replace this repo with a fork of sarrus implementation

### ISSUE THREAD

**Issue by maximee-leroyy** [srcdslab/sm-plugin-Discord#3]
https://github.com/Sarrus1/DiscordWebhookAPI

**Comment by Rushaway** [comment]
Cannot wait to work embed feature. 👍

**Comment by maximee-leroyy** [comment]
Forked it here :slightly_smiling_face: 

https://github.com/srcdslab/sm-plugin-DiscordWebhookAPI
